export class JapaneseCharacter {
  constructor(character, romaji, category, type) {
    this.character = character // The hiragana character
    this.romaji = romaji // Romanized reading
    this.category = category // 'base', 'dakuten', 'combination', or 'handakuten'
    this.type = type // 'hiragana' or 'katakana' or 'kanji'
  }
}

export const hiraganaList = [
  // Base Characters
  new JapaneseCharacter('あ', 'a', 'base', 'hiragana'),
  new JapaneseCharacter('い', 'i', 'base', 'hiragana'),
  new JapaneseCharacter('う', 'u', 'base', 'hiragana'),
  new JapaneseCharacter('え', 'e', 'base', 'hiragana'),
  new JapaneseCharacter('お', 'o', 'base', 'hiragana'),
  new JapaneseCharacter('か', 'ka', 'base', 'hiragana'),
  new JapaneseCharacter('き', 'ki', 'base', 'hiragana'),
  new JapaneseCharacter('く', 'ku', 'base', 'hiragana'),
  new JapaneseCharacter('け', 'ke', 'base', 'hiragana'),
  new JapaneseCharacter('こ', 'ko', 'base', 'hiragana'),
  new JapaneseCharacter('さ', 'sa', 'base', 'hiragana'),
  new JapaneseCharacter('し', 'shi', 'base', 'hiragana'),
  new JapaneseCharacter('す', 'su', 'base', 'hiragana'),
  new JapaneseCharacter('せ', 'se', 'base', 'hiragana'),
  new JapaneseCharacter('そ', 'so', 'base', 'hiragana'),
  new JapaneseCharacter('た', 'ta', 'base', 'hiragana'),
  new JapaneseCharacter('ち', 'chi', 'base', 'hiragana'),
  new JapaneseCharacter('つ', 'tsu', 'base', 'hiragana'),
  new JapaneseCharacter('て', 'te', 'base', 'hiragana'),
  new JapaneseCharacter('と', 'to', 'base', 'hiragana'),
  new JapaneseCharacter('な', 'na', 'base', 'hiragana'),
  new JapaneseCharacter('に', 'ni', 'base', 'hiragana'),
  new JapaneseCharacter('ぬ', 'nu', 'base', 'hiragana'),
  new JapaneseCharacter('ね', 'ne', 'base', 'hiragana'),
  new JapaneseCharacter('の', 'no', 'base', 'hiragana'),
  new JapaneseCharacter('は', 'ha', 'base', 'hiragana'),
  new JapaneseCharacter('ひ', 'hi', 'base', 'hiragana'),
  new JapaneseCharacter('ふ', 'fu', 'base', 'hiragana'),
  new JapaneseCharacter('へ', 'he', 'base', 'hiragana'),
  new JapaneseCharacter('ほ', 'ho', 'base', 'hiragana'),
  new JapaneseCharacter('ま', 'ma', 'base', 'hiragana'),
  new JapaneseCharacter('み', 'mi', 'base', 'hiragana'),
  new JapaneseCharacter('む', 'mu', 'base', 'hiragana'),
  new JapaneseCharacter('め', 'me', 'base', 'hiragana'),
  new JapaneseCharacter('も', 'mo', 'base', 'hiragana'),
  new JapaneseCharacter('や', 'ya', 'base', 'hiragana'),
  new JapaneseCharacter('ゆ', 'yu', 'base', 'hiragana'),
  new JapaneseCharacter('よ', 'yo', 'base', 'hiragana'),
  new JapaneseCharacter('ら', 'ra', 'base', 'hiragana'),
  new JapaneseCharacter('り', 'ri', 'base', 'hiragana'),
  new JapaneseCharacter('る', 'ru', 'base', 'hiragana'),
  new JapaneseCharacter('れ', 're', 'base', 'hiragana'),
  new JapaneseCharacter('ろ', 'ro', 'base', 'hiragana'),
  new JapaneseCharacter('わ', 'wa', 'base', 'hiragana'),
  new JapaneseCharacter('を', 'wo', 'base', 'hiragana'),
  new JapaneseCharacter('ん', 'n', 'base', 'hiragana'),

  // Dakuten Characters
  new JapaneseCharacter('が', 'ga', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぎ', 'gi', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぐ', 'gu', 'dakuten', 'hiragana'),
  new JapaneseCharacter('げ', 'ge', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ご', 'go', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ざ', 'za', 'dakuten', 'hiragana'),
  new JapaneseCharacter('じ', 'ji', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ず', 'zu', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぜ', 'ze', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぞ', 'zo', 'dakuten', 'hiragana'),
  new JapaneseCharacter('だ', 'da', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぢ', 'ji', 'dakuten', 'hiragana'),
  new JapaneseCharacter('づ', 'zu', 'dakuten', 'hiragana'),
  new JapaneseCharacter('で', 'de', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ど', 'do', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ば', 'ba', 'dakuten', 'hiragana'),
  new JapaneseCharacter('び', 'bi', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぶ', 'bu', 'dakuten', 'hiragana'),
  new JapaneseCharacter('べ', 'be', 'dakuten', 'hiragana'),
  new JapaneseCharacter('ぼ', 'bo', 'dakuten', 'hiragana'),

  // Handakuten Characters
  new JapaneseCharacter('ぱ', 'pa', 'handakuten', 'hiragana'),
  new JapaneseCharacter('ぴ', 'pi', 'handakuten', 'hiragana'),
  new JapaneseCharacter('ぷ', 'pu', 'handakuten', 'hiragana'),
  new JapaneseCharacter('ぺ', 'pe', 'handakuten', 'hiragana'),
  new JapaneseCharacter('ぽ', 'po', 'handakuten', 'hiragana'),

  // Combination Characters
  new JapaneseCharacter('きゃ', 'kya', 'combination', 'hiragana'),
  new JapaneseCharacter('きゅ', 'kyu', 'combination', 'hiragana'),
  new JapaneseCharacter('きょ', 'kyo', 'combination', 'hiragana'),
  new JapaneseCharacter('しゃ', 'sha', 'combination', 'hiragana'),
  new JapaneseCharacter('しゅ', 'shu', 'combination', 'hiragana'),
  new JapaneseCharacter('しょ', 'sho', 'combination', 'hiragana'),
  new JapaneseCharacter('ちゃ', 'cha', 'combination', 'hiragana'),
  new JapaneseCharacter('ちゅ', 'chu', 'combination', 'hiragana'),
  new JapaneseCharacter('ちょ', 'cho', 'combination', 'hiragana'),
  new JapaneseCharacter('にゃ', 'nya', 'combination', 'hiragana'),
  new JapaneseCharacter('にゅ', 'nyu', 'combination', 'hiragana'),
  new JapaneseCharacter('にょ', 'nyo', 'combination', 'hiragana'),
  new JapaneseCharacter('ひゃ', 'hya', 'combination', 'hiragana'),
  new JapaneseCharacter('ひゅ', 'hyu', 'combination', 'hiragana'),
  new JapaneseCharacter('ひょ', 'hyo', 'combination', 'hiragana'),
  new JapaneseCharacter('みゃ', 'mya', 'combination', 'hiragana'),
  new JapaneseCharacter('みゅ', 'myu', 'combination', 'hiragana'),
  new JapaneseCharacter('みょ', 'myo', 'combination', 'hiragana'),
  new JapaneseCharacter('りゃ', 'rya', 'combination', 'hiragana'),
  new JapaneseCharacter('りゅ', 'ryu', 'combination', 'hiragana'),
  new JapaneseCharacter('りょ', 'ryo', 'combination', 'hiragana'),
  new JapaneseCharacter('ぎゃ', 'gya', 'combination', 'hiragana'),
  new JapaneseCharacter('ぎゅ', 'gyu', 'combination', 'hiragana'),
  new JapaneseCharacter('ぎょ', 'gyo', 'combination', 'hiragana'),
  new JapaneseCharacter('じゃ', 'ja', 'combination', 'hiragana'),
  new JapaneseCharacter('じゅ', 'ju', 'combination', 'hiragana'),
  new JapaneseCharacter('じょ', 'jo', 'combination', 'hiragana'),
  new JapaneseCharacter('びゃ', 'bya', 'combination', 'hiragana'),
  new JapaneseCharacter('びゅ', 'byu', 'combination', 'hiragana'),
  new JapaneseCharacter('びょ', 'byo', 'combination', 'hiragana'),
  new JapaneseCharacter('ぴゃ', 'pya', 'combination', 'hiragana'),
  new JapaneseCharacter('ぴゅ', 'pyu', 'combination', 'hiragana'),
  new JapaneseCharacter('ぴょ', 'pyo', 'combination', 'hiragana')
]

export const katakanaList = [
  // Base Katakana
  new JapaneseCharacter('ア', 'a', 'base', 'katakana'),
  new JapaneseCharacter('イ', 'i', 'base', 'katakana'),
  new JapaneseCharacter('ウ', 'u', 'base', 'katakana'),
  new JapaneseCharacter('エ', 'e', 'base', 'katakana'),
  new JapaneseCharacter('オ', 'o', 'base', 'katakana'),
  new JapaneseCharacter('カ', 'ka', 'base', 'katakana'),
  new JapaneseCharacter('キ', 'ki', 'base', 'katakana'),
  new JapaneseCharacter('ク', 'ku', 'base', 'katakana'),
  new JapaneseCharacter('ケ', 'ke', 'base', 'katakana'),
  new JapaneseCharacter('コ', 'ko', 'base', 'katakana'),
  new JapaneseCharacter('サ', 'sa', 'base', 'katakana'),
  new JapaneseCharacter('シ', 'shi', 'base', 'katakana'),
  new JapaneseCharacter('ス', 'su', 'base', 'katakana'),
  new JapaneseCharacter('セ', 'se', 'base', 'katakana'),
  new JapaneseCharacter('ソ', 'so', 'base', 'katakana'),
  new JapaneseCharacter('タ', 'ta', 'base', 'katakana'),
  new JapaneseCharacter('チ', 'chi', 'base', 'katakana'),
  new JapaneseCharacter('ツ', 'tsu', 'base', 'katakana'),
  new JapaneseCharacter('テ', 'te', 'base', 'katakana'),
  new JapaneseCharacter('ト', 'to', 'base', 'katakana'),
  new JapaneseCharacter('ナ', 'na', 'base', 'katakana'),
  new JapaneseCharacter('ニ', 'ni', 'base', 'katakana'),
  new JapaneseCharacter('ヌ', 'nu', 'base', 'katakana'),
  new JapaneseCharacter('ネ', 'ne', 'base', 'katakana'),
  new JapaneseCharacter('ノ', 'no', 'base', 'katakana'),
  new JapaneseCharacter('ハ', 'ha', 'base', 'katakana'),
  new JapaneseCharacter('ヒ', 'hi', 'base', 'katakana'),
  new JapaneseCharacter('フ', 'fu', 'base', 'katakana'),
  new JapaneseCharacter('ヘ', 'he', 'base', 'katakana'),
  new JapaneseCharacter('ホ', 'ho', 'base', 'katakana'),
  new JapaneseCharacter('マ', 'ma', 'base', 'katakana'),
  new JapaneseCharacter('ミ', 'mi', 'base', 'katakana'),
  new JapaneseCharacter('ム', 'mu', 'base', 'katakana'),
  new JapaneseCharacter('メ', 'me', 'base', 'katakana'),
  new JapaneseCharacter('モ', 'mo', 'base', 'katakana'),
  new JapaneseCharacter('ヤ', 'ya', 'base', 'katakana'),
  new JapaneseCharacter('ユ', 'yu', 'base', 'katakana'),
  new JapaneseCharacter('ヨ', 'yo', 'base', 'katakana'),
  new JapaneseCharacter('ラ', 'ra', 'base', 'katakana'),
  new JapaneseCharacter('リ', 'ri', 'base', 'katakana'),
  new JapaneseCharacter('ル', 'ru', 'base', 'katakana'),
  new JapaneseCharacter('レ', 're', 'base', 'katakana'),
  new JapaneseCharacter('ロ', 'ro', 'base', 'katakana'),
  new JapaneseCharacter('ワ', 'wa', 'base', 'katakana'),
  new JapaneseCharacter('ヲ', 'wo', 'base', 'katakana'),
  new JapaneseCharacter('ン', 'n', 'base', 'katakana'),

  // Dakuten Katakana
  new JapaneseCharacter('ガ', 'ga', 'dakuten', 'katakana'),
  new JapaneseCharacter('ギ', 'gi', 'dakuten', 'katakana'),
  new JapaneseCharacter('グ', 'gu', 'dakuten', 'katakana'),
  new JapaneseCharacter('ゲ', 'ge', 'dakuten', 'katakana'),
  new JapaneseCharacter('ゴ', 'go', 'dakuten', 'katakana'),
  new JapaneseCharacter('ザ', 'za', 'dakuten', 'katakana'),
  new JapaneseCharacter('ジ', 'ji', 'dakuten', 'katakana'),
  new JapaneseCharacter('ズ', 'zu', 'dakuten', 'katakana'),
  new JapaneseCharacter('ゼ', 'ze', 'dakuten', 'katakana'),
  new JapaneseCharacter('ゾ', 'zo', 'dakuten', 'katakana'),
  new JapaneseCharacter('ダ', 'da', 'dakuten', 'katakana'),
  new JapaneseCharacter('ヂ', 'ji', 'dakuten', 'katakana'),
  new JapaneseCharacter('ヅ', 'zu', 'dakuten', 'katakana'),
  new JapaneseCharacter('デ', 'de', 'dakuten', 'katakana'),
  new JapaneseCharacter('ド', 'do', 'dakuten', 'katakana'),
  new JapaneseCharacter('バ', 'ba', 'dakuten', 'katakana'),
  new JapaneseCharacter('ビ', 'bi', 'dakuten', 'katakana'),
  new JapaneseCharacter('ブ', 'bu', 'dakuten', 'katakana'),
  new JapaneseCharacter('ベ', 'be', 'dakuten', 'katakana'),
  new JapaneseCharacter('ボ', 'bo', 'dakuten', 'katakana'),

  // Handakuten Katakana
  new JapaneseCharacter('パ', 'pa', 'handakuten', 'katakana'),
  new JapaneseCharacter('ピ', 'pi', 'handakuten', 'katakana'),
  new JapaneseCharacter('プ', 'pu', 'handakuten', 'katakana'),
  new JapaneseCharacter('ペ', 'pe', 'handakuten', 'katakana'),
  new JapaneseCharacter('ポ', 'po', 'handakuten', 'katakana'),

  // Combination Katakana
  new JapaneseCharacter('キャ', 'kya', 'combination', 'katakana'),
  new JapaneseCharacter('キュ', 'kyu', 'combination', 'katakana'),
  new JapaneseCharacter('キョ', 'kyo', 'combination', 'katakana'),
  new JapaneseCharacter('シャ', 'sha', 'combination', 'katakana'),
  new JapaneseCharacter('シュ', 'shu', 'combination', 'katakana'),
  new JapaneseCharacter('ショ', 'sho', 'combination', 'katakana'),
  new JapaneseCharacter('チャ', 'cha', 'combination', 'katakana'),
  new JapaneseCharacter('チュ', 'chu', 'combination', 'katakana'),
  new JapaneseCharacter('チョ', 'cho', 'combination', 'katakana'),
  new JapaneseCharacter('ニャ', 'nya', 'combination', 'katakana'),
  new JapaneseCharacter('ニュ', 'nyu', 'combination', 'katakana'),
  new JapaneseCharacter('ニョ', 'nyo', 'combination', 'katakana'),
  new JapaneseCharacter('ヒャ', 'hya', 'combination', 'katakana'),
  new JapaneseCharacter('ヒュ', 'hyu', 'combination', 'katakana'),
  new JapaneseCharacter('ヒョ', 'hyo', 'combination', 'katakana'),
  new JapaneseCharacter('ミャ', 'mya', 'combination', 'katakana'),
  new JapaneseCharacter('ミュ', 'myu', 'combination', 'katakana'),
  new JapaneseCharacter('ミョ', 'myo', 'combination', 'katakana'),
  new JapaneseCharacter('リャ', 'rya', 'combination', 'katakana'),
  new JapaneseCharacter('リュ', 'ryu', 'combination', 'katakana'),
  new JapaneseCharacter('リョ', 'ryo', 'combination', 'katakana')
]
