export class JapaneseCharacter {
  constructor(character, romaji, category) {
    this.character = character // The hiragana character
    this.romaji = romaji // Romanized reading
    this.category = category // 'base', 'dakuten', 'combination', or 'handakuten'
  }
}

export const hiraganaList = [
  // Base Characters
  new JapaneseCharacter('あ', 'a', 'base'),
  new JapaneseCharacter('い', 'i', 'base'),
  new JapaneseCharacter('う', 'u', 'base'),
  new JapaneseCharacter('え', 'e', 'base'),
  new JapaneseCharacter('お', 'o', 'base'),
  new JapaneseCharacter('か', 'ka', 'base'),
  new JapaneseCharacter('き', 'ki', 'base'),
  new JapaneseCharacter('く', 'ku', 'base'),
  new JapaneseCharacter('け', 'ke', 'base'),
  new JapaneseCharacter('こ', 'ko', 'base'),
  new JapaneseCharacter('さ', 'sa', 'base'),
  new JapaneseCharacter('し', 'shi', 'base'),
  new JapaneseCharacter('す', 'su', 'base'),
  new JapaneseCharacter('せ', 'se', 'base'),
  new JapaneseCharacter('そ', 'so', 'base'),
  new JapaneseCharacter('た', 'ta', 'base'),
  new JapaneseCharacter('ち', 'chi', 'base'),
  new JapaneseCharacter('つ', 'tsu', 'base'),
  new JapaneseCharacter('て', 'te', 'base'),
  new JapaneseCharacter('と', 'to', 'base'),
  new JapaneseCharacter('な', 'na', 'base'),
  new JapaneseCharacter('に', 'ni', 'base'),
  new JapaneseCharacter('ぬ', 'nu', 'base'),
  new JapaneseCharacter('ね', 'ne', 'base'),
  new JapaneseCharacter('の', 'no', 'base'),
  new JapaneseCharacter('は', 'ha', 'base'),
  new JapaneseCharacter('ひ', 'hi', 'base'),
  new JapaneseCharacter('ふ', 'fu', 'base'),
  new JapaneseCharacter('へ', 'he', 'base'),
  new JapaneseCharacter('ほ', 'ho', 'base'),
  new JapaneseCharacter('ま', 'ma', 'base'),
  new JapaneseCharacter('み', 'mi', 'base'),
  new JapaneseCharacter('む', 'mu', 'base'),
  new JapaneseCharacter('め', 'me', 'base'),
  new JapaneseCharacter('も', 'mo', 'base'),
  new JapaneseCharacter('や', 'ya', 'base'),
  new JapaneseCharacter('ゆ', 'yu', 'base'),
  new JapaneseCharacter('よ', 'yo', 'base'),
  new JapaneseCharacter('ら', 'ra', 'base'),
  new JapaneseCharacter('り', 'ri', 'base'),
  new JapaneseCharacter('る', 'ru', 'base'),
  new JapaneseCharacter('れ', 're', 'base'),
  new JapaneseCharacter('ろ', 'ro', 'base'),
  new JapaneseCharacter('わ', 'wa', 'base'),
  new JapaneseCharacter('を', 'wo', 'base'),
  new JapaneseCharacter('ん', 'n', 'base'),

  // Dakuten Characters
  new JapaneseCharacter('が', 'ga', 'dakuten'),
  new JapaneseCharacter('ぎ', 'gi', 'dakuten'),
  new JapaneseCharacter('ぐ', 'gu', 'dakuten'),
  new JapaneseCharacter('げ', 'ge', 'dakuten'),
  new JapaneseCharacter('ご', 'go', 'dakuten'),
  new JapaneseCharacter('ざ', 'za', 'dakuten'),
  new JapaneseCharacter('じ', 'ji', 'dakuten'),
  new JapaneseCharacter('ず', 'zu', 'dakuten'),
  new JapaneseCharacter('ぜ', 'ze', 'dakuten'),
  new JapaneseCharacter('ぞ', 'zo', 'dakuten'),
  new JapaneseCharacter('だ', 'da', 'dakuten'),
  new JapaneseCharacter('ぢ', 'ji', 'dakuten'),
  new JapaneseCharacter('づ', 'zu', 'dakuten'),
  new JapaneseCharacter('で', 'de', 'dakuten'),
  new JapaneseCharacter('ど', 'do', 'dakuten'),
  new JapaneseCharacter('ば', 'ba', 'dakuten'),
  new JapaneseCharacter('び', 'bi', 'dakuten'),
  new JapaneseCharacter('ぶ', 'bu', 'dakuten'),
  new JapaneseCharacter('べ', 'be', 'dakuten'),
  new JapaneseCharacter('ぼ', 'bo', 'dakuten'),

  // Handakuten Characters
  new JapaneseCharacter('ぱ', 'pa', 'handakuten'),
  new JapaneseCharacter('ぴ', 'pi', 'handakuten'),
  new JapaneseCharacter('ぷ', 'pu', 'handakuten'),
  new JapaneseCharacter('ぺ', 'pe', 'handakuten'),
  new JapaneseCharacter('ぽ', 'po', 'handakuten'),

  // Combination Characters
  new JapaneseCharacter('きゃ', 'kya', 'combination'),
  new JapaneseCharacter('きゅ', 'kyu', 'combination'),
  new JapaneseCharacter('きょ', 'kyo', 'combination'),
  new JapaneseCharacter('しゃ', 'sha', 'combination'),
  new JapaneseCharacter('しゅ', 'shu', 'combination'),
  new JapaneseCharacter('しょ', 'sho', 'combination'),
  new JapaneseCharacter('ちゃ', 'cha', 'combination'),
  new JapaneseCharacter('ちゅ', 'chu', 'combination'),
  new JapaneseCharacter('ちょ', 'cho', 'combination'),
  new JapaneseCharacter('にゃ', 'nya', 'combination'),
  new JapaneseCharacter('にゅ', 'nyu', 'combination'),
  new JapaneseCharacter('にょ', 'nyo', 'combination'),
  new JapaneseCharacter('ひゃ', 'hya', 'combination'),
  new JapaneseCharacter('ひゅ', 'hyu', 'combination'),
  new JapaneseCharacter('ひょ', 'hyo', 'combination'),
  new JapaneseCharacter('みゃ', 'mya', 'combination'),
  new JapaneseCharacter('みゅ', 'myu', 'combination'),
  new JapaneseCharacter('みょ', 'myo', 'combination'),
  new JapaneseCharacter('りゃ', 'rya', 'combination'),
  new JapaneseCharacter('りゅ', 'ryu', 'combination'),
  new JapaneseCharacter('りょ', 'ryo', 'combination'),
  new JapaneseCharacter('ぎゃ', 'gya', 'combination'),
  new JapaneseCharacter('ぎゅ', 'gyu', 'combination'),
  new JapaneseCharacter('ぎょ', 'gyo', 'combination'),
  new JapaneseCharacter('じゃ', 'ja', 'combination'),
  new JapaneseCharacter('じゅ', 'ju', 'combination'),
  new JapaneseCharacter('じょ', 'jo', 'combination'),
  new JapaneseCharacter('びゃ', 'bya', 'combination'),
  new JapaneseCharacter('びゅ', 'byu', 'combination'),
  new JapaneseCharacter('びょ', 'byo', 'combination'),
  new JapaneseCharacter('ぴゃ', 'pya', 'combination'),
  new JapaneseCharacter('ぴゅ', 'pyu', 'combination'),
  new JapaneseCharacter('ぴょ', 'pyo', 'combination')
]
